apiVersion: apps/v1
kind: Deployment
metadata:
  name: sj-self-serve-api
  namespace: pulse
  labels:
    app:  sj-self-serve-api
spec:
  selector:
    matchLabels:
      app: sj-self-serve-api
  # replicas: 1
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  sj-self-serve-api
    spec:
      
      containers:
      - name:  sj-self-serve-api
        image:  ccpcontainerregistry.azurecr.io/sj-self-serge-api-qa:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sj-self-serve-api
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  sj-self-serve-api
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sj-self-serve-api
  namespace: pulse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: sj-self-serve-api