apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sj-self-serve-api
  namespace: demo-sj-self-serve-api
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  tls:
    - hosts:
        - demo-sj-self-serve-api.kognitiv.com
      secretName: kognitiv-com-full-cert
  rules:
    - host: demo-sj-self-serve-api.kognitiv.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sj-self-serve-api
                port:
                  number: 80